nestjsx/crud

- README.md
- dist/README.md
Hi there,
My first contribution to this repo :tada: but nothing to be proud about. Jokes aside, you've done a really great work! Thanks for your dedication to Nest.
> fix(doc): typo

- src/typeorm/repository-service.class.ts
> fix: always persist only defined primary keys

- packages/crud/src/services/crud-service.abstract.ts
With a total of 41 items, the pageCount should be 5 whereas it was returning 4
179
> Wanted to add a test but wasn't sure how? Existing tests still pass
> fix(Pagination): Fixed pageCount number

- packages/util/src/checks.util.ts
- packages/util/test/checks.util.spec.ts
fix #161
@Bnaya @sgrebnov have a look
> fix(util): ISO Date string validation

- packages/crud/src/crud/validation.helper.ts
> fix(crud): add Entity swagger to `BulkDto#list`

- packages/crud-typeorm/src/typeorm-crud.service.ts
- packages/crud-typeorm/test/0.basic-crud.spec.ts
Added count to TypeOrmCrudService. Think it'll be handy :)
> feat(crud): added count binding to typeorm crud

- README.md
Fixed the contributing link in the read me to code of conduct
> docs(readme): Fixed link

- integration/crud-typeorm/projects/index.ts
- integration/crud-typeorm/projects/project.entity.ts
- integration/crud-typeorm/projects/user-project.entity.ts
- integration/crud-typeorm/seeds.ts
- integration/crud-typeorm/users-licenses/index.ts
- integration/crud-typeorm/users-licenses/license.entity.ts
- integration/crud-typeorm/users-licenses/user-license.entity.ts
- integration/crud-typeorm/users/user.entity.ts
- packages/crud-typeorm/src/typeorm-crud.service.ts
- packages/crud-typeorm/test/b.query-params.spec.ts
- packages/crud-typeorm/test/c.basic-crud.spec.ts
Fixed composite key join
Co-authored-by: mkelandis <landis.michael@gmail.com>
> fix(typeorm):  composite key join

- docker-compose.yml
- jest.config.js
- package.json
- packages/crud-request/test/request-query.builder.spec.ts
- packages/crud/src/interfaces/crud-request.interface.ts
- yarn.lock
Jest tests
Co-authored-by: Diluka <pmars42@gmail.com>
> fix(jest): test ts files without build

- integration/crud-typeorm/app.module.ts
- integration/crud-typeorm/devices/device.entity.ts
- integration/crud-typeorm/devices/devices.controller.ts
- integration/crud-typeorm/devices/devices.module.ts
- integration/crud-typeorm/devices/devices.service.ts
- integration/crud-typeorm/devices/index.ts
- packages/crud/src/crud/crud-routes.factory.ts
- packages/crud/src/module/crud-config.service.ts
> fix(crud): primary param fix and swagger

- packages/crud-typeorm/src/typeorm-crud.service.ts
fix #51
Co-authored-by: NKJe <n@nk.je>
> fix(typeorm): entity events

- packages/crud-typeorm/test/b.query-params.spec.ts
close #197 
too many changes up to now
and still 
> `...found` is redundant
> test(crud-typeorm): add test from #197

- packages/crud-request/src/request-query.parser.ts
- packages/crud/src/crud/crud-routes.factory.ts
- packages/crud/src/crud/swagger.helper.ts
- packages/crud/src/crud/validation.helper.ts
- packages/crud/src/interfaces/crud-options.interface.ts
- packages/crud/src/interfaces/dto-options.interface.ts
- packages/crud/src/interfaces/index.ts
- packages/crud/test/__fixture__/dto/index.ts
- packages/crud/test/__fixture__/dto/test-create.dto.ts
- packages/crud/test/__fixture__/dto/test-update.dto.ts
- packages/crud/test/crud.dto.options.spec.ts
> feat(crud): added dto options

- packages/crud/src/interfaces/crud-controller.interface.ts
The return should not be a single object.
> Update Create Many return type to be type T[]

- packages/crud/src/crud/crud-routes.factory.ts
- packages/crud/src/crud/serialize.helper.ts
- packages/crud/src/crud/swagger.helper.ts
- packages/crud/src/interceptors/crud-response.interceptor.ts
- packages/crud/src/interfaces/serialize-options.interface.ts
- packages/crud/test/crud.serialize.options.spec.ts
> fix(crud): updated CrudSerializeInterceptor, swagger response models

- packages/crud-request/src/request-query.validator.ts
> fix(request): operators validation

- packages/crud-request/src/request-query.parser.ts
- packages/crud-request/src/types/request-query.types.ts
> fix(request): parser validation with new operators

- packages/crud/src/services/crud-service.abstract.ts
> fix(crud): get primary param filed

- packages/crud/src/interceptors/crud-request.interceptor.ts
- packages/crud/test/crud.decorator.base.spec.ts
- packages/crud/test/crud.decorator.override.spec.ts
- packages/crud/test/crud.dto.options.spec.ts
> fix(request): request validation error code 400

- packages/crud/src/crud/crud-routes.factory.ts
- packages/crud/src/crud/swagger.helper.ts
Hi, 
I try to fix issue #355 
This is my commits. 
Please check it. 
I noticed that when run example app and get json, there is an undefined path on open api json.
Unfortunately I was unable to understand the problem.
> fix(crud) - add unique operationId and description response on swagger

- package.json
- packages/crud/src/crud/swagger.helper.ts
- packages/crud/test/crud.decorator.override.spec.ts
- yarn.lock
It's always disturbed me :) 
Next up - a feature to allow override of default auto generated Swagger actions.
> [FIX] Swagger text - plural fix for resources

- README.md
Please check if your PR fulfills the following requirements:
What kind of change does this PR introduce?
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] Tests
[ ] Release
[ ] CI related changes
[x] Other... Please describe:
```
Issue Number: N/A
```
[ ] Yes
[ ] No
```
> chore: added Stand With Ukraine banner

- README.md
Please check if your PR fulfills the following requirements:
What kind of change does this PR introduce?
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] Tests
[ ] Release
[ ] CI related changes
[ ] Other... Please describe:
```
Issue Number: N/A
```
[ ] Yes
[ ] No
```
> chore: added link to my story in readme
